name: Auto-approve Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
    - name: Set context variables
      id: set-context
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          const regex = /^-?\s*\[([xX ])\].*(?:$)/mg;
          const matches = Array.from(context.payload.pull_request.body.matchAll(regex));
          const allChecked = matches.every((match) => match[1].toLowerCase() === 'x');

          console.log(`ALL_CHECKED=${allChecked}\n`);
          fs.appendFileSync(process.env.GITHUB_OUTPUT, `ALL_CHECKED=${allChecked}\n`);

    - name: Auto-approve if checkboxes are checked
      if: steps.set-context.outputs.ALL_CHECKED == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE',
          });

          console.log('Pull request approved.');
