name: Auto-approve Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
    - name: Set context variables
      id: set-context
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');

          const regex = /^-?\s*\[([xX ])\].*(?:$)/mg;
          const matches = Array.from(context.payload.pull_request.body.matchAll(regex));
          const allChecked = matches.every((match) => match[1].toLowerCase() === 'x');
          
          fs.appendFileSync(process.env.GITHUB_ENV, `allChecked=${allChecked}\n`);

    - name: Auto-approve if checkboxes are checked
      if: steps.set-context.outputs.allChecked == 'true'
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          async function run() {
            const pullRequest = context.payload.pull_request;

            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
              event: 'APPROVE',
            });

            console.log('Pull request approved.');
          }

          run();
