name: Auto-approve Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
    - name: Auto-approve if checkboxes are checked
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { context, github } = require('github-script');
          
          async function run() {
            const pullRequest = context.payload.pull_request;

            const checkboxes = pullRequest.body.match(/\[( |x)\]/g) || [];

            const allChecked = checkboxes.every((checkbox) => checkbox.toLowerCase() === '[x]');

            if (allChecked) {
              await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequest.number,
                event: 'APPROVE',
              });

              console.log('Pull request approved.');
            } else {
              console.log('Not all checkboxes are checked. Pull request not approved.');
            }
          }

          run();
